apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ printf "%s" (include "doris.frontend.name" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: doris-frontend
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: doris-frontend
  serviceName: {{ printf "%s" (include "doris.frontend.name" .) }}
  {{- if .Values.frontend.updateStrategy }}
  updateStrategy: {{- toYaml .Values.frontend.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: doris-frontend
        {{- if .Values.frontend.podLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.frontend.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.frontend.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.frontend.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "doris.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.frontend.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.frontend.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.frontend.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "doris.serviceAccountName" . }}
      {{- if .Values.frontend.priorityClassName }}
      priorityClassName: {{ .Values.frontend.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.frontend.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.frontend.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.frontend.podAffinityPreset "component" "doris" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.frontend.podAntiAffinityPreset "component" "doris" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.frontend.nodeAffinityPreset.type "key" .Values.frontend.nodeAffinityPreset.key "values" .Values.frontend.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.frontend.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.frontend.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.frontend.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.spreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.frontend.spreadConstraints "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.shareProcessNamespace }}
      shareProcessNamespace: {{ .Values.frontend.shareProcessNamespace }}
      {{- end }}
      {{- if .Values.frontend.schedulerName }}
      schedulerName: {{ .Values.frontend.schedulerName | quote }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.frontend.terminationGracePeriodSeconds }}
      containers:
        - name: frontend
          image: {{ template "doris.frontend.image" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | quote }}
          {{- if .Values.frontend.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.frontend.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.frontend.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.frontend.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.frontend.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.frontend.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.frontend.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: DEBUG
              value: {{ ternary "true" "false" (or .Values.frontend.image.debug .Values.diagnosticMode.enabled) | quote }}
            - name: BUILD_TYPE
              value: "k8s"
            - name: FE_INIT_NUMBER
              value: "{{ .Values.frontend.replicaCount }}"
            - name: CN_SERVICE
              value: "{{ printf "%s" (include "doris.backend-cn.name" .) }}"
            - name: CN_STATEFULSET
              value: "{{ printf "%s" (include "doris.backend-cn.name" .) }}"
            - name: BE_SERVICE
              value: "{{ printf "%s" (include "doris.backend.name" .) }}"
            - name: BE_STATEFULSET
              value: "{{ printf "%s" (include "doris.backend.name" .) }}"
            - name: FE_SERVICE
              value: "{{ printf "%s" (include "doris.frontend.name" .) }}"
            - name: FE_STATEFULSET
              value: "{{ printf "%s" (include "doris.frontend.name" .) }}"
            - name: APP_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http-port
              containerPort: {{ .Values.frontend.containerPort.httpPort }}
            - name: rpc-port
              containerPort: {{ .Values.frontend.containerPort.rpcPort }}
            - name: query-port
              containerPort: {{ .Values.frontend.containerPort.queryPort }}
            - name: edit-log-port
              containerPort: {{ .Values.frontend.containerPort.editLogPort }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.frontend.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: {{ add1 .Values.frontend.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.frontend.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.frontend.livenessProbe.failureThreshold }}
            tcpSocket:
              port: {{ .Values.frontend.containerPort.rpcPort }}
          {{- else if .Values.frontend.customLivenessProbe }}
          livenessProbe: {{- toYaml .Values.frontend.customLivenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ add1 .Values.frontend.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.frontend.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.frontend.readinessProbe.failureThreshold }}
            tcpSocket:
              port: {{ .Values.frontend.containerPort.rpcPort }}
          {{- else if .Values.frontend.customReadinessProbe }}
          readinessProbe: {{- toYaml .Values.frontend.customReadinessProbe | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.frontend.resources }}
          resources: {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: doris-data
              mountPath: {{ .Values.frontend.persistence.path }}
              subPath: {{ .Values.frontend.persistence.subPath }}
            - name: conf
              mountPath: /opt/apache-doris/fe/conf
              #In order to call the api of k8s
            - name: kube
              mountPath: /root/.kube/config
              readOnly: true
            {{- if .Values.frontend.extraVolumeMounts }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.frontend.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
        {{- if .Values.frontend.sidecars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.frontend.sidecars "context" $) | nindent 8 }}
        {{- end }}
      {{- $needsVolumePermissions := and .Values.volumePermissions.enabled .Values.frontend.persistence.enabled .Values.frontend.podSecurityContext.enabled .Values.frontend.containerSecurityContext.enabled }}        
      {{- if or .Values.frontend.initContainers $needsVolumePermissions .Values.sysctl.enabled }}
      initContainers:
        {{- if .Values.frontend.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.frontend.initContainers "context" $) | nindent 8 }}
        {{- end }}
        {{- if $needsVolumePermissions }}
        - name: volume-permissions
          image: {{ include "doris.volumePermissions.image" . }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
          command:
            - /bin/bash
            - -ec
            - |
              {{- if eq ( toString ( .Values.volumePermissions.containerSecurityContext.runAsUser )) "auto" }}
              chown -R `id -u`:`id -G | cut -d " " -f2` {{ .Values.frontend.persistence.path }}
              {{- else }}
              chown -R {{ .Values.frontend.containerSecurityContext.runAsUser }}:{{ .Values.frontend.podSecurityContext.fsGroup }} {{ .Values.frontend.persistence.path }}
              {{- end }}
          {{- if eq ( toString ( .Values.volumePermissions.containerSecurityContext.runAsUser )) "auto" }}
          securityContext: {{- omit .Values.volumePermissions.containerSecurityContext "runAsUser" | toYaml | nindent 12 }}
          {{- else }}
          securityContext: {{- .Values.volumePermissions.containerSecurityContext | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: doris-data
              mountPath: {{ .Values.frontend.persistence.path }}
              subPath: {{ .Values.frontend.persistence.subPath }}
        {{- end }}
        {{- if .Values.sysctl.enabled }}
        - name: init-sysctl
          image: {{ include "doris.sysctl.image" . }}
          imagePullPolicy: {{ default "" .Values.sysctl.image.pullPolicy | quote }}
          securityContext:
            privileged: true
            runAsUser: 0
          {{- if .Values.sysctl.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.sysctl.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.sysctl.resources }}
          resources: {{- toYaml .Values.sysctl.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.sysctl.mountHostSys }}
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
        {{- if .Values.sysctl.mountHostSys }}
        - name: host-sys
          hostPath:
            path: /sys
        {{- end }}
        - name: conf
          configMap:
            name: {{ printf "%s" (include "doris.frontend.name" .) }}
        - name: kube
          hostPath:
            path: /root/.kube/config
        {{- if .Values.frontend.extraVolumes }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.frontend.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
  {{- if not .Values.frontend.persistence.enabled }}
        - name: doris-data
          emptyDir: {}
  {{- else if .Values.frontend.persistence.existingClaim }}
        - name: doris-data
          persistentVolumeClaim:
            claimName: {{ printf "%s" (tpl .Values.frontend.persistence.existingClaim .) }}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: doris-data
        labels: {{- include "common.labels.matchLabels" . | nindent 10 }}
          app.kubernetes.io/component: frontend
        {{- if .Values.frontend.persistence.annotations }}
        annotations: {{- toYaml .Values.frontend.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.frontend.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.frontend.persistence.size | quote }}
        {{- if .Values.frontend.persistence.selector }}
        selector: {{- include "common.tplvalues.render" (dict "value" .Values.frontend.persistence.selector "context" $) | nindent 10 }}
        {{- end }}
        {{- include "common.storage.class" (dict "persistence" .Values.frontend.persistence "global" .Values.global) | nindent 8 }}
  {{- end }}