apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ printf "%s-journalnode" (include "hdfs.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: journalnode
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.journalnode.replicaCount }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: journalnode
  serviceName: {{ printf "%s-jn-headless" (include "hdfs.fullname" .) | trunc 63 | trimSuffix "-"  }}
  {{- if .Values.journalnode.updateStrategy }}
  updateStrategy: {{- toYaml .Values.journalnode.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: journalnode
        {{- if .Values.journalnode.podLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.journalnode.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.journalnode.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.journalnode.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "hdfs.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.journalnode.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.journalnode.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.journalnode.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.journalnode.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "hdfs.serviceAccountName" . }}
      {{- if .Values.journalnode.priorityClassName }}
      priorityClassName: {{ .Values.journalnode.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.journalnode.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.journalnode.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.journalnode.podAffinityPreset "component" "hdfs" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.journalnode.podAntiAffinityPreset "component" "hdfs" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.journalnode.nodeAffinityPreset.type "key" .Values.journalnode.nodeAffinityPreset.key "values" .Values.journalnode.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.journalnode.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.journalnode.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.journalnode.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.journalnode.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.journalnode.spreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.journalnode.spreadConstraints "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.journalnode.shareProcessNamespace }}
      shareProcessNamespace: {{ .Values.journalnode.shareProcessNamespace }}
      {{- end }}
      {{- if .Values.journalnode.schedulerName }}
      schedulerName: {{ .Values.journalnode.schedulerName | quote }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.journalnode.terminationGracePeriodSeconds }}
      containers:
        - name: journalnode
          image: {{ template "hdfs.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.journalnode.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.journalnode.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.journalnode.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.journalnode.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.journalnode.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.journalnode.command "context" $) | nindent 12 }}
          {{- else }}
          command:
            - /bin/bash
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.journalnode.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.journalnode.args "context" $) | nindent 12 }}
          {{- else }}
          args:
            - -c
            - hdfs journalnode
          {{- end }}
          env:
            - name: DEBUG
              value: {{ ternary "true" "false" (or .Values.image.debug .Values.diagnosticMode.enabled) | quote }}
          ports:
            - name: jn-http
              containerPort: {{ .Values.journalnode.containerPort.httpPort }}
            - name: jn-rpc
              containerPort: {{ .Values.journalnode.containerPort.rpcPort }}

          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.journalnode.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.journalnode.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.journalnode.livenessProbe.periodSeconds }}
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: {{ add1 .Values.journalnode.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.journalnode.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.journalnode.livenessProbe.failureThreshold }}
            tcpSocket:
              port: {{ .Values.journalnode.containerPort.httpPort }}
          {{- else if .Values.journalnode.customLivenessProbe }}
          livenessProbe: {{- toYaml .Values.journalnode.customLivenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.journalnode.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.journalnode.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.journalnode.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ add1 .Values.journalnode.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.journalnode.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.journalnode.readinessProbe.failureThreshold }}
            tcpSocket:
              port: {{ .Values.journalnode.containerPort.httpPort }}
          {{- else if .Values.journalnode.customReadinessProbe }}
          readinessProbe: {{- toYaml .Values.journalnode.customReadinessProbe | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.journalnode.resources }}
          resources: {{- toYaml .Values.journalnode.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: hdfs-data
              mountPath: {{ .Values.journalnode.persistence.path }}
              subPath: {{ .Values.journalnode.persistence.subPath }}
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop/core-site.xml"
              subPath: "core-site.xml"
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop/hdfs-site.xml"
              subPath: "hdfs-site.xml"
            - name: hadoop-env-sh
              mountPath: "/opt/hadoop/etc/hadoop/hadoop-env.sh"
              subPath: "hadoop-env.sh"
            {{- if .Values.journalnode.extraVolumeMounts }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.journalnode.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
        {{- if .Values.journalnode.sidecars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.journalnode.sidecars "context" $) | nindent 8 }}
        {{- end }}
      {{- $needsVolumePermissions := and .Values.volumePermissions.enabled .Values.journalnode.persistence.enabled .Values.journalnode.podSecurityContext.enabled .Values.journalnode.containerSecurityContext.enabled }}
      {{- if or .Values.journalnode.initContainers $needsVolumePermissions .Values.sysctl.enabled }}
      initContainers:
        {{- if .Values.journalnode.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.journalnode.initContainers "context" $) | nindent 8 }}
        {{- end }}
        {{- if $needsVolumePermissions }}
        - name: volume-permissions
          image: {{ include "hdfs.volumePermissions.image" . }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
          command:
            - /bin/bash
            - -ec
            - |
              {{- if eq ( toString ( .Values.volumePermissions.containerSecurityContext.runAsUser )) "auto" }}
              chown -R `id -u`:`id -G | cut -d " " -f2` {{ .Values.journalnode.persistence.path }}
              {{- else }}
              chown -R {{ .Values.journalnode.containerSecurityContext.runAsUser }}:{{ .Values.journalnode.podSecurityContext.fsGroup }} {{ .Values.journalnode.persistence.path }}
              {{- end }}
          {{- if eq ( toString ( .Values.volumePermissions.containerSecurityContext.runAsUser )) "auto" }}
          securityContext: {{- omit .Values.volumePermissions.containerSecurityContext "runAsUser" | toYaml | nindent 12 }}
          {{- else }}
          securityContext: {{- .Values.volumePermissions.containerSecurityContext | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: hdfs-data
              mountPath: {{ .Values.journalnode.persistence.path }}
              subPath: {{ .Values.journalnode.persistence.subPath }}
        {{- end }}
        {{- if .Values.sysctl.enabled }}
        - name: init-sysctl
          image: {{ include "hdfs.sysctl.image" . }}
          imagePullPolicy: {{ default "" .Values.sysctl.image.pullPolicy | quote }}
          securityContext:
            privileged: true
            runAsUser: 0
          {{- if .Values.sysctl.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.sysctl.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.sysctl.resources }}
          resources: {{- toYaml .Values.sysctl.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.sysctl.mountHostSys }}
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ printf "%s-configmap" (include "hdfs.fullname" .) }}
        - name: hadoop-env-sh
          configMap:
            name: {{ printf "%s-jn-configmap" (include "hdfs.fullname" .) }}
        {{- if .Values.sysctl.mountHostSys }}
        - name: host-sys
          hostPath:
            path: /sys
        {{- end }}
        {{- if .Values.journalnode.extraVolumes }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.journalnode.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
  {{- if not .Values.journalnode.persistence.enabled }}
        - name: hdfs-data
          emptyDir: {}
  {{- else if .Values.journalnode.persistence.existingClaim }}
        - name: hdfs-data
          persistentVolumeClaim:
            claimName: {{ printf "%s" (tpl .Values.journalnode.persistence.existingClaim .) }}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: hdfs-data
        labels: {{- include "common.labels.matchLabels" . | nindent 10 }}
          app.kubernetes.io/component: journalnode
        {{- if .Values.journalnode.persistence.annotations }}
        annotations: {{- toYaml .Values.journalnode.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.journalnode.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.journalnode.persistence.size | quote }}
        {{- if .Values.journalnode.persistence.selector }}
        selector: {{- include "common.tplvalues.render" (dict "value" .Values.journalnode.persistence.selector "context" $) | nindent 10 }}
        {{- end }}
        {{- include "common.storage.class" (dict "persistence" .Values.journalnode.persistence "global" .Values.global) | nindent 8 }}
  {{- end }}