apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s" (include "doris.backend.name" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: doris-backend
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.backend.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.backend.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.backend.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  {{ if eq .Values.backend.service.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.backend.service.externalTrafficPolicy }}
  {{- end }}
  {{- if and (eq .Values.backend.service.type "LoadBalancer") .Values.backend.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.backend.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.backend.service.type "LoadBalancer") .Values.backend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.backend.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if and (eq .Values.backend.service.type "ClusterIP") .Values.backend.service.clusterIP }}
  clusterIP: {{ .Values.backend.service.clusterIP }}
  {{- end }}
  ports:
    - name: be-port
      port: {{ .Values.backend.service.port.port }}
      {{- if and (or (eq .Values.backend.service.type "NodePort") (eq .Values.backend.service.type "LoadBalancer")) .Values.backend.service.nodePort }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- else if eq .Values.backend.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: webserver-port
      port: {{ .Values.backend.service.port.webServerPort }}
      {{- if and (or (eq .Values.backend.service.type "NodePort") (eq .Values.backend.service.type "LoadBalancer")) .Values.backend.service.nodePort }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- else if eq .Values.backend.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: heartbeat-port
      port: {{ .Values.backend.service.port.heatbeatPort }}
      {{- if and (or (eq .Values.backend.service.type "NodePort") (eq .Values.backend.service.type "LoadBalancer")) .Values.backend.service.nodePort }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- else if eq .Values.backend.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: brpc-port
      port: {{ .Values.backend.service.port.brpcPort }}
      {{- if and (or (eq .Values.backend.service.type "NodePort") (eq .Values.backend.service.type "LoadBalancer")) .Values.backend.service.nodePort }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- else if eq .Values.backend.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: doris-backend
