{{- if .Values.backendcn.enabled }}
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ printf "%s" (include "doris.backendcn.name" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: doris-backendcn
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.backendcn.replicaCount }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: doris-backendcn
  serviceName: {{ printf "%s" (include "doris.backendcn.name" .) }}
  {{- if .Values.backendcn.updateStrategy }}
  updateStrategy: {{- toYaml .Values.backendcn.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: doris-backendcn
        {{- if .Values.backendcn.podLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.backendcn.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.backendcn.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.backendcn.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "doris.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.backendcn.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.backendcn.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.backendcn.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.backendcn.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "doris.serviceAccountName" . }}
      {{- if .Values.backendcn.priorityClassName }}
      priorityClassName: {{ .Values.backendcn.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.backendcn.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.backendcn.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.backendcn.podAffinityPreset "component" "doris" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.backendcn.podAntiAffinityPreset "component" "doris" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.backendcn.nodeAffinityPreset.type "key" .Values.backendcn.nodeAffinityPreset.key "values" .Values.backendcn.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.backendcn.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.backendcn.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.backendcn.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.backendcn.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.backendcn.spreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.backendcn.spreadConstraints "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.backendcn.shareProcessNamespace }}
      shareProcessNamespace: {{ .Values.backendcn.shareProcessNamespace }}
      {{- end }}
      {{- if .Values.backendcn.schedulerName }}
      schedulerName: {{ .Values.backendcn.schedulerName | quote }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.backendcn.terminationGracePeriodSeconds }}
      containers:
        - name: backendcn
          image: {{ template "doris.backendcn.image" . }}
          imagePullPolicy: {{ .Values.backendcn.image.pullPolicy | quote }}
          {{- if .Values.backendcn.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.backendcn.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.backendcn.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.backendcn.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.backendcn.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.backendcn.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.backendcn.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.backendcn.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: DEBUG
              value: {{ ternary "true" "false" (or .Values.backendcn.image.debug .Values.diagnosticMode.enabled) | quote }}
            - name: BUILD_TYPE
              value: "k8s"
          ports:
            - name: be-port
              containerPort: {{ .Values.backendcn.containerPort.port }}
            - name: webserver-port
              containerPort: {{ .Values.backendcn.containerPort.webServerPort }}
            - name: heartbeat-port
              containerPort: {{ .Values.backendcn.containerPort.heatbeatPort }}
            - name: brpc-port
              containerPort: {{ .Values.backendcn.containerPort.brpcPort }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.backendcn.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.backendcn.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backendcn.livenessProbe.periodSeconds }}
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: {{ add1 .Values.backendcn.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.backendcn.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.backendcn.livenessProbe.failureThreshold }}
            tcpSocket:
              port: {{ .Values.backendcn.containerPort.port }}
          {{- else if .Values.backendcn.customLivenessProbe }}
          livenessProbe: {{- toYaml .Values.backendcn.customLivenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.backendcn.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.backendcn.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backendcn.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ add1 .Values.backendcn.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.backendcn.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.backendcn.readinessProbe.failureThreshold }}
            tcpSocket:
              port: {{ .Values.backendcn.containerPort.port }}
          {{- else if .Values.backendcn.customReadinessProbe }}
          readinessProbe: {{- toYaml .Values.backendcn.customReadinessProbe | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.backendcn.resources }}
          resources: {{- toYaml .Values.backendcn.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: doris-data
              mountPath: {{ .Values.backendcn.persistence.path }}
              subPath: {{ .Values.backendcn.persistence.subPath }}
            - name: conf
              mountPath: /opt/apache-doris/be/conf
              #In order to call the api of k8s
            - name: sys
              mountPath: /etc/pki
              readOnly: true
            {{- if .Values.backendcn.extraVolumeMounts }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.backendcn.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
        {{- if .Values.backendcn.sidecars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.backendcn.sidecars "context" $) | nindent 8 }}
        {{- end }}
      {{- $needsVolumePermissions := and .Values.volumePermissions.enabled .Values.backendcn.persistence.enabled .Values.backendcn.podSecurityContext.enabled .Values.backendcn.containerSecurityContext.enabled }}        
      {{- if or .Values.backendcn.initContainers $needsVolumePermissions .Values.sysctl.enabled }}
      initContainers:
        {{- if .Values.backendcn.initContainers }}
        {{- include "common.tplvalues.render" (dict "value" .Values.backendcn.initContainers "context" $) | nindent 8 }}
        {{- end }}
        {{- if $needsVolumePermissions }}
        - name: volume-permissions
          image: {{ include "doris.volumePermissions.image" . }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
          command:
            - /bin/bash
            - -ec
            - |
              {{- if eq ( toString ( .Values.volumePermissions.containerSecurityContext.runAsUser )) "auto" }}
              chown -R `id -u`:`id -G | cut -d " " -f2` {{ .Values.backendcn.persistence.path }}
              {{- else }}
              chown -R {{ .Values.backendcn.containerSecurityContext.runAsUser }}:{{ .Values.backendcn.podSecurityContext.fsGroup }} {{ .Values.backendcn.persistence.path }}
              {{- end }}
          {{- if eq ( toString ( .Values.volumePermissions.containerSecurityContext.runAsUser )) "auto" }}
          securityContext: {{- omit .Values.volumePermissions.containerSecurityContext "runAsUser" | toYaml | nindent 12 }}
          {{- else }}
          securityContext: {{- .Values.volumePermissions.containerSecurityContext | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: doris-data
              mountPath: {{ .Values.backendcn.persistence.path }}
              subPath: {{ .Values.backendcn.persistence.subPath }}
        {{- end }}
        {{- if .Values.sysctl.enabled }}
        - name: init-sysctl
          image: {{ include "doris.sysctl.image" . }}
          imagePullPolicy: {{ default "" .Values.sysctl.image.pullPolicy | quote }}
          securityContext:
            privileged: true
            runAsUser: 0
          {{- if .Values.sysctl.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.sysctl.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.sysctl.resources }}
          resources: {{- toYaml .Values.sysctl.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.sysctl.mountHostSys }}
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
        {{- if .Values.sysctl.mountHostSys }}
        - name: host-sys
          hostPath:
            path: /sys
        {{- end }}
        - name: conf
          configMap:
            name: {{ printf "%s" (include "doris.backendcn.name" .) }}
        - name: sys
          hostPath:
            path: /etc/pki
        {{- if .Values.backendcn.extraVolumes }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.backendcn.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
  {{- if not .Values.backendcn.persistence.enabled }}
        - name: doris-data
          emptyDir: {}
  {{- else if .Values.backendcn.persistence.existingClaim }}
        - name: doris-data
          persistentVolumeClaim:
            claimName: {{ printf "%s" (tpl .Values.backendcn.persistence.existingClaim .) }}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: doris-data
        labels: {{- include "common.labels.matchLabels" . | nindent 10 }}
          app.kubernetes.io/component: backendcn
        {{- if .Values.backendcn.persistence.annotations }}
        annotations: {{- toYaml .Values.backendcn.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.backendcn.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.backendcn.persistence.size | quote }}
        {{- if .Values.backendcn.persistence.selector }}
        selector: {{- include "common.tplvalues.render" (dict "value" .Values.backendcn.persistence.selector "context" $) | nindent 10 }}
        {{- end }}
        {{- include "common.storage.class" (dict "persistence" .Values.backendcn.persistence "global" .Values.global) | nindent 8 }}
  {{- end }}
{{- end }}